
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Be My Valentine?</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            text-align: center;
            background-color: #ffe6e6;
            transition: background 0.5s;
        }
        .container {
            margin-top: 20vh;
        }
        .question {
            font-size: 2em;
            font-weight: bold;
            color: #d63384;
        }
        .buttons {
            margin-top: 20px;
        }
        button {
            font-size: 1.5em;
            padding: 10px 20px;
            margin: 10px;
            border: none;
            cursor: pointer;
            border-radius: 10px;
            transition: 0.3s;
        }
        .yes {
            background-color: #ff4d6d;
            color: white;
        }
        .no {
            background-color: #444;
            color: white;
        }
        .hidden {
            display: none;
        }
        .hearts {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            pointer-events: none;
            overflow: hidden;
        }
        .heart {
            position: absolute;
            font-size: 2em;
            color: red;
            animation: float 3s linear infinite;
        }
        @keyframes float {
            from {
                transform: translateY(100vh);
                opacity: 1;
            }
            to {
                transform: translateY(-10vh);
                opacity: 0;
            }
        }
    </style>
</head>
<body>
    <div class="container" id="question-container">
        <p class="question">Will you be my Valentine? ❤️</p>
        <div class="buttons">
            <button class="yes" onclick="sayYes()">Yes</button>
            <button class="no" onclick="sayNo()">No</button>
        </div>
    </div>
    
    <div class="hidden" id="yes-container">
        <h1>YAY! ❤️❤️❤️</h1>
        <p>You're the best Valentine ever!</p>
        <div class="hearts" id="hearts"></div>
    </div>
    
    <div class="hidden" id="no-container">
        <h1>Must have been a misclick hahaha 😆</h1>
        <p>Thanks for being my Valentine!</p>
    </div>
    
    <script>
        function sayYes() {
            document.getElementById('question-container').classList.add('hidden');
            document.getElementById('yes-container').classList.remove('hidden');
            createHearts();
        }

        function sayNo() {
            document.getElementById('question-container').classList.add('hidden');
            document.getElementById('no-container').classList.remove('hidden');
        }

        function createHearts() {
            const heartsContainer = document.getElementById('hearts');
            for (let i = 0; i < 30; i++) {
                let heart = document.createElement('div');
                heart.classList.add('heart');
                heart.innerHTML = '❤️';
                heart.style.left = Math.random() * 100 + 'vw';
                heart.style.animationDuration = (Math.random() * 2 + 2) + 's';
                heartsContainer.appendChild(heart);

                setTimeout(() => {
                    heart.remove();
                }, 3000);
            }
        }
    </script>
</body>
</html>
